import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayOut from "@/Component/LayOut/LayOut";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayOut>
        {children}
        <Toaster
  position="bottom-right"
  reverseOrder={false}
/>

        </LayOut>
       
        </body>
    </html>
  );
}
